# docker-compose.yaml
version: '3.3'
services:
  user-db:
    image: mariadb:${DB_VERSION}
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_USER: ${USER_DB_USER} # 设置用户名
      MYSQL_PASSWORD: ${USER_DB_PASSWORD} # 设置用户民吗
      MYSQL_DATABASE: ${USER_DB_DATABASE} # 初始数据库
      MYSQL_ROOT_PASSWORD: ${USER_DB_ROOT_PASSWORD} # root用户密码
    ports:
      - ${USER_DB_PORT}:3306
    volumes:
      - ./data/server-db:/var/lib/mysql
    networks:
      - micro-network

  consul:
    image: consul
    command: ["agent", "-dev", "-client=0.0.0.0"]
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
    restart: always
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "datacenter": "dc1",
          "ui_config": {
            "enabled": true
          }
        }
    networks:
      - micro-network

networks:
  micro-network:
    external: true