// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/869413421/micro-chat/app/chat/admin/internal/biz"
	"github.com/869413421/micro-chat/app/chat/admin/internal/conf"
	"github.com/869413421/micro-chat/app/chat/admin/internal/data"
	"github.com/869413421/micro-chat/app/chat/admin/internal/server"
	"github.com/869413421/micro-chat/app/chat/admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, userClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUseCase(userRepo, logger)
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleUsecase := biz.NewRoleUseCase(roleRepo, logger)
	permissionRepo := data.NewPermissionRepo(dataData, logger)
	permissionUsecase := biz.NewPermissionUseCase(permissionRepo, logger)
	chatAdmin := service.NewChatAdmin(userUsecase, roleUsecase, permissionUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, chatAdmin, logger)
	httpServer := server.NewHTTPServer(confServer, auth, chatAdmin, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
